Repository RCSIndustries/Project-Generator, pull requests merged in 2023-08, with the labels that each got.

#7 6 split up backend front end projects in the repo
  .env
  .env.local
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/api/placeholder
  client/src/index.js
  client/src/reportWebVitals.js
  client/src/web/common/placeholder
  client/src/web/pages/placeholder
  middleware.ts
  next.config.js
  package-lock.json
  package.json
  server/app.js
  server/config/db/placeholder
  server/config/middleware/placeholder
  server/config/routes/placeholder
  server/config/routes/routes.js
  server/controller/placeholder
  server/controller/rootcontroller.js
  server/models/placeholder
  server/package-lock.json
  server/package.json
  server/server.js
  server/services/placeholder
Labels: Refactor

#9 3 initial backend for project ideas
  package-lock.json
  server/config/db/connection.js
  server/config/db/placeholder
  server/config/routes/placeholder
  server/config/routes/routes.js
  server/controller/placeholder
  server/controller/projectcontroller.js
  server/controller/rootcontroller.js
  server/models/idea.js
  server/package-lock.json
  server/package.json
  server/server.js
  server/services/projectService.js
  server/tsconfig.json
Labels: Feature, Refactor

#11 10 backend
  server/config/routes/routes.js
  server/controller/projectcontroller.js
  server/models/placeholder
  server/services/placeholder
  server/services/projectService.js
Labels: Feature

#19 Proper ENV Variables
  server/config/db/connection.js
  server/server.js
Labels: Story, Feature, Refactor

#22 8 define version 1s data collection specifications
  server/controller/projectcontroller.js
  server/exampledata/gpt.csv
  server/models/idea.js
  server/services/projectService.js
  server/utils/dataparser.js
  template-generator/placeholder
Labels: Refactor, Analysis

#23 21 convert js to ts
  server/config/db/connection.ts
  server/config/routes/routes.ts
  server/controller/projectcontroller.ts
  server/controller/rootcontroller.js
  server/controller/rootcontroller.ts
  server/package-lock.json
  server/package.json
  server/server.ts
  server/services/projectService.ts
Labels: Refactor

#25 Primary UI Project
  client/.gitignore
  client/next-env.d.ts
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/App.tsx
  client/src/api/placeholder
  client/src/index.js
  client/src/index.tsx
  client/src/reportWebVitals.js
  client/src/web/common/ResponseiveNavBar/ResponsiveNavBar.tsx
  client/src/web/common/ResponseiveNavBar/index.ts
  client/src/web/common/placeholder
  client/src/web/pages/placeholder
  client/tsconfig.json
Labels: Refactor

#26 12 admin backend
  server/config/routes/adminroutes.ts
  server/config/routes/routes.ts
  server/controller/admincontroller.ts
  server/controller/authcontroller.ts
  server/controller/projectcontroller.ts
  server/server.ts
  server/services/admin.service.ts
  server/services/projectService.ts
Labels: Feature

#28 12 admin backend
  client/package-lock.json
  client/package.json
  server/config/routes/adminroutes.ts
  server/controller/admincontroller.ts
  server/package-lock.json
  server/package.json
  server/services/admin.service.ts
Labels: Refactor
