Repository RCSIndustries/Project-Generator, pull requests merged in 2023-09, with the labels that each got.

#36 34 implement initial generation UI
  client/generate-react-cli.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/index.tsx
  client/src/services/generator/useGeneratorServices.tsx
  client/src/web/common/GenerateBtn/Generatebtn.tsx
  client/src/web/components/Generator/Generator.tsx
  client/src/web/components/Generator/index.ts
  client/src/web/components/maps/maps.ts
  client/tsconfig.json
  server/exampledata/gpt2.csv
  server/package-lock.json
  server/package.json
  server/server.ts
Labels: Feature

#37 34 implement initial generation UI
  .dockerignore
  DOCKERFILE
  client/src/App.tsx
  client/src/services/generator/useGeneratorServices.tsx
  client/src/web/common/GenerateBtn/Generatebtn.tsx
  client/src/web/components/Generator/Generator.tsx
  server/config/routes/routes.ts
Labels: Feature

#44 40 dockerize application
  .dockerignore
  DOCKERFILE
  client/Dockerfile
  client/Dockerfile.prod
  client/package-lock.json
  client/package.json
  docker-compose.yml
  package-lock.json
  package.json
  run.sh
  server/Dockerfile
  server/Dockerfile.prod
  server/package-lock.json
  server/package.json
Labels: Story, Feature, Release

#45 40 dockerize application
  client/Dockerfile.prod
  client/package.json
  docker-compose.yml
  run.sh
  server/Dockerfile.prod
Labels: Feature

#46 Github Actions Setup
  .github/workflows/deploy-api.yml
  .github/workflows/deploy-web.yml
Labels: Feature

#47 Update useGeneratorServices.tsx
  client/src/services/generator/useGeneratorServices.tsx
Labels: Defect, Refactor

#48 Quick typo
  server/server.ts
Labels: Defect, Refactor

#49 Quick typo
  server/server.ts
Labels: Refactor
